"use client";

import { DropdownMenu } from "radix-ui";
import { Archive, BriefcaseBusiness, Building2, FileText, MoreHorizontal, Package, PencilLine, Plus, Search, Truck } from "lucide-react";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Dialog, DialogClose, DialogContent } from "../animate-ui/overlay";
import { RippleButton } from "../animate-ui/ripple-button";
import { ErrorState, ToastViewport, useToasts } from "../ui/feedback";
import { api, ApiError } from "../../lib/api/client";
import type { CatalogKind, CatalogRecord } from "../../lib/api/types";
import { formatMoney, formatNumber } from "../../lib/format";

type UiKind = "materiales" | "empleados" | "desplazamientos" | "proveedores" | "textos";
const config: Record<UiKind, { api: CatalogKind; title: string; singular: string; description: string; icon: typeof Package }> = {
  materiales: { api: "materials", title: "Materiales", singular: "material", description: "Costes, precios habituales y referencias de proveedor.", icon: Package },
  empleados: { api: "employees", title: "Empleados", singular: "empleado", description: "Tarifas horarias habituales para líneas de mano de obra.", icon: BriefcaseBusiness },
  desplazamientos: { api: "travels", title: "Desplazamientos", singular: "desplazamiento", description: "Conceptos recurrentes de transporte, salida y kilometraje.", icon: Truck },
  proveedores: { api: "suppliers", title: "Proveedores", singular: "proveedor", description: "Directorio breve para identificar el origen de materiales.", icon: Building2 },
  textos: { api: "text-templates", title: "Textos habituales", singular: "texto", description: "Plantillas reutilizables para condiciones, garantías y protección de datos.", icon: FileText },
};

export function CatalogPage({ kind }: { kind: UiKind }) {
  const item = config[kind]; const Icon = item.icon; const [records, setRecords] = useState<CatalogRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<CatalogRecord | "new" | null>(null); const { toasts, push } = useToasts();
  const load = useCallback(async () => { setLoading(true); setError(""); try { setRecords(await api.getCatalog(item.api)); } catch (cause) { setError(cause instanceof ApiError && cause.status === 503 ? "La API no está disponible." : "No se pudo cargar este catálogo."); } finally { setLoading(false); } }, [item.api]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => records.filter((record) => recordName(record).toLowerCase().includes(query.toLowerCase())), [query, records]);
  async function archive(record: CatalogRecord) { try { await api.archiveCatalog(item.api, record.id); push(`${capitalize(item.singular)} desactivado`); await load(); } catch { push("No se pudo actualizar el registro", "error"); } }
  return <div className="page"><div className="page-header"><div><p className="eyebrow">Catálogo</p><h1 className="page-title">{item.title}</h1><p className="page-subtitle">{item.description}</p></div><div className="header-actions"><RippleButton onClick={() => setEditing("new")}><Plus />Nuevo {item.singular}</RippleButton></div></div>
    <div className="toolbar"><label className="search-field"><Search /><span className="sr-only">Buscar</span><input className="input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Buscar ${item.title.toLowerCase()}…`} /></label></div>
    {loading ? <div className="catalog-grid">{Array.from({ length: 6 }, (_, index) => <div className="skeleton" style={{ height: 170 }} key={index} />)}</div> : error ? <div className="panel"><ErrorState message={error} onRetry={() => void load()} /></div> : visible.length === 0 ? <div className="panel empty-state"><div><div className="empty-icon"><Icon /></div><h3>{query ? "No hay coincidencias" : `Aún no hay ${item.title.toLowerCase()}`}</h3><p>{query ? "Prueba con otro término." : `Crea el primer ${item.singular} para utilizarlo en presupuestos.`}</p>{!query ? <RippleButton onClick={() => setEditing("new")}><Plus />Crear {item.singular}</RippleButton> : null}</div></div> : <div className="catalog-grid">{visible.map((record) => <article className="panel catalog-card" key={record.id}><div className="catalog-card-head"><div><h3>{recordName(record)}</h3><p>{recordSubtitle(record)}</p></div><DropdownMenu.Root><DropdownMenu.Trigger asChild><button className="button button-ghost button-icon" aria-label="Acciones"><MoreHorizontal /></button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="dropdown-content" align="end"><DropdownMenu.Item className="dropdown-item" onSelect={() => setEditing(record)}><PencilLine />Editar</DropdownMenu.Item>{"active" in record && record.active ? <DropdownMenu.Item className="dropdown-item danger" onSelect={() => void archive(record)}><Archive />Desactivar</DropdownMenu.Item> : null}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root></div><div className="catalog-values">{recordValues(record).map(([label, value]) => <div className="catalog-value" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></article>)}</div>}
    <CatalogDialog kind={kind} apiKind={item.api} record={editing} open={Boolean(editing)} onOpenChange={(open) => { if (!open) setEditing(null); }} onSaved={async (message) => { setEditing(null); push(message); await load(); }} /><ToastViewport toasts={toasts} />
  </div>;
}

function CatalogDialog({ kind, apiKind, record, open, onOpenChange, onSaved }: { kind: UiKind; apiKind: CatalogKind; record: CatalogRecord | "new" | null; open: boolean; onOpenChange: (open: boolean) => void; onSaved: (message: string) => void }) {
  const existing = record && record !== "new" ? record : null; const [form, setForm] = useState<Record<string, string | boolean>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const fields = fieldConfig(kind);
  useEffect(() => { const initial: Record<string, string | boolean> = {}; fields.forEach((field) => { const source = existing as unknown as Record<string, unknown> | null; initial[field.key] = source?.[field.key] as string | boolean ?? field.defaultValue ?? ""; }); setForm(initial); setError(""); }, [existing, open, kind]); // eslint-disable-line react-hooks/exhaustive-deps
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const payload = { ...form, name: String(form.name ?? form.title ?? "") }; if (existing) await api.updateCatalog(apiKind, existing.id, payload); else await api.createCatalog(apiKind, payload); onSaved(existing ? "Registro actualizado" : "Registro creado"); } catch { setError("No se pudo guardar. Revisa los campos."); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent title={`${existing ? "Editar" : "Nuevo"} ${config[kind].singular}`} description="Estos valores son habituales; cada presupuesto conserva su propio snapshot editable." footer={<><DialogClose asChild><RippleButton variant="secondary">Cancelar</RippleButton></DialogClose><RippleButton type="submit" form="catalog-form" disabled={busy}>{busy ? "Guardando…" : "Guardar"}</RippleButton></>}><form id="catalog-form" onSubmit={submit} className="form-grid">{fields.map((field) => { const fieldId = `catalog-${kind}-${field.key}`; return field.type === "textarea" ? <div className="field span-2" key={field.key}><label className="field-label" htmlFor={fieldId}>{field.label}</label><textarea id={fieldId} className="textarea" value={String(form[field.key] ?? "")} onChange={(event) => setForm((current) => ({ ...current, [field.key]: event.target.value }))} required={field.required} /></div> : field.type === "checkbox" ? <label className="panel span-2" key={field.key} style={{ display: "flex", alignItems: "center", gap: 10, padding: 12 }}><input id={fieldId} type="checkbox" checked={Boolean(form[field.key])} onChange={(event) => setForm((current) => ({ ...current, [field.key]: event.target.checked }))} />{field.label}</label> : <div className={`field${field.full ? " span-2" : ""}`} key={field.key}><label className="field-label" htmlFor={fieldId}>{field.label}</label><input id={fieldId} className="input" value={String(form[field.key] ?? "")} onChange={(event) => setForm((current) => ({ ...current, [field.key]: event.target.value }))} inputMode={field.numeric ? "decimal" : undefined} required={field.required} /></div>; })}{error ? <p className="error-text span-2">{error}</p> : null}</form></DialogContent></Dialog>;
}

type Field = { key: string; label: string; type?: "input" | "textarea" | "checkbox"; defaultValue?: string | boolean; full?: boolean; numeric?: boolean; required?: boolean };
function fieldConfig(kind: UiKind): Field[] { if (kind === "materiales") return [{ key: "name", label: "Nombre", full: true, required: true }, { key: "supplierNameSnapshot", label: "Proveedor" }, { key: "supplierCode", label: "Código proveedor" }, { key: "unit", label: "Unidad", defaultValue: "ud" }, { key: "supplierUnitPrice", label: "Coste / PVP proveedor", numeric: true }, { key: "saleUnitPrice", label: "Venta habitual", numeric: true }, { key: "igicRate", label: "IGIC %", defaultValue: "7", numeric: true }, { key: "description", label: "Descripción", type: "textarea" }]; if (kind === "empleados") return [{ key: "name", label: "Nombre", full: true, required: true }, { key: "costRate", label: "Coste / hora", defaultValue: "0", numeric: true }, { key: "saleRate", label: "Venta / hora", defaultValue: "0", numeric: true }, { key: "defaultIgicRate", label: "IGIC %", defaultValue: "7", numeric: true }]; if (kind === "desplazamientos") return [{ key: "name", label: "Nombre", full: true, required: true }, { key: "unit", label: "Unidad", defaultValue: "km" }, { key: "costUnitPrice", label: "Coste / unidad", defaultValue: "0", numeric: true }, { key: "saleUnitPrice", label: "Venta / unidad", defaultValue: "0", numeric: true }, { key: "igicRate", label: "IGIC %", defaultValue: "7", numeric: true }, { key: "description", label: "Descripción", type: "textarea" }]; if (kind === "proveedores") return [{ key: "name", label: "Nombre", full: true, required: true }, { key: "taxId", label: "NIF / CIF" }]; return [{ key: "title", label: "Título", full: true, required: true }, { key: "body", label: "Contenido", type: "textarea", required: true }, { key: "alwaysInclude", label: "Incluir por defecto", type: "checkbox", defaultValue: false }]; }
function recordName(record: CatalogRecord) { return "title" in record ? record.title : record.name; }
function recordSubtitle(record: CatalogRecord) { if ("supplierNameSnapshot" in record) return record.supplierNameSnapshot || record.supplierCode || "Sin proveedor"; if ("body" in record) return record.body.slice(0, 90); if ("taxId" in record) return record.taxId || "Sin NIF/CIF"; if ("description" in record) return record.description || record.unit; return "Tarifa habitual"; }
function recordValues(record: CatalogRecord): Array<[string, string]> { if ("supplierUnitPrice" in record) return [["Coste", formatMoney(record.supplierUnitPrice)], ["Venta", formatMoney(record.saleUnitPrice)], ["Unidad", record.unit], ["IGIC", `${formatNumber(record.igicRate)} %`]]; if ("costRate" in record) return [["Coste / h", formatMoney(record.costRate)], ["Venta / h", formatMoney(record.saleRate)], ["IGIC", `${formatNumber(record.defaultIgicRate)} %`], ["Estado", record.active ? "Activo" : "Inactivo"]]; if ("costUnitPrice" in record) return [["Coste", formatMoney(record.costUnitPrice)], ["Venta", formatMoney(record.saleUnitPrice)], ["Unidad", record.unit], ["Estado", record.active ? "Activo" : "Inactivo"]]; if ("alwaysInclude" in record) return [["Por defecto", record.alwaysInclude ? "Sí" : "No"], ["Estado", record.active ? "Activo" : "Inactivo"]]; return [["Estado", record.active ? "Activo" : "Inactivo"]]; }
function capitalize(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
