"use client";

import { Mail, MapPin, PencilLine, Phone, Plus, Search, Users } from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Dialog, DialogClose, DialogContent } from "../animate-ui/overlay";
import { RippleButton } from "../animate-ui/ripple-button";
import { ErrorState, RevisionConflictDialog, ToastViewport, useToasts } from "../ui/feedback";
import { api, ApiError } from "../../lib/api/client";
import type { ClientRecord } from "../../lib/api/types";
import { formatDate } from "../../lib/format";

export function ClientsPage() {
  const [clients, setClients] = useState<ClientRecord[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<ClientRecord | "new" | null>(null); const [conflict, setConflict] = useState(false); const { toasts, push } = useToasts();
  const load = useCallback(async (search = query) => { setLoading(true); setError(""); try { setClients(await api.searchClients(search)); } catch (cause) { setError(cause instanceof ApiError && cause.status === 503 ? "La API no está disponible." : "No se pudieron consultar los clientes."); } finally { setLoading(false); } }, [query]);
  useEffect(() => { const id = window.setTimeout(() => void load(query), 220); return () => clearTimeout(id); }, [query]); // eslint-disable-line react-hooks/exhaustive-deps
  return <div className="page page-narrow"><div className="page-header"><div><p className="eyebrow">Directorio</p><h1 className="page-title">Clientes</h1><p className="page-subtitle">La información imprescindible para preparar presupuestos. Sin convertirlo en un CRM.</p></div><div className="header-actions"><RippleButton onClick={() => setEditing("new")}><Plus />Nuevo cliente</RippleButton></div></div>
    <div className="toolbar"><label className="search-field"><Search /><span className="sr-only">Buscar clientes</span><input className="input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nombre o email…" /></label></div>
    <div className="panel table-wrap">{loading ? <div style={{ padding: 16, display: "grid", gap: 10 }}>{Array.from({ length: 5 }, (_, index) => <div className="skeleton" style={{ height: 54 }} key={index} />)}</div> : error ? <ErrorState message={error} onRetry={() => void load()} /> : clients.length === 0 ? <div className="empty-state"><div><div className="empty-icon"><Users /></div><h3>{query ? "No hay coincidencias" : "Aún no hay clientes"}</h3><p>{query ? "Prueba con otro término de búsqueda." : "Crea el primer cliente y podrás asociarlo a un presupuesto."}</p>{!query ? <RippleButton onClick={() => setEditing("new")}><Plus />Crear cliente</RippleButton> : null}</div></div> : <table className="data-table"><thead><tr><th>Cliente</th><th>Contacto</th><th>Dirección</th><th>Actualizado</th><th></th></tr></thead><tbody>{clients.map((client) => <tr key={client.id}><td><span className="row-title">{client.name}</span><span className="row-subtitle">{client.taxId || "Sin NIF/CIF"}</span></td><td>{client.email ? <span style={{ display: "flex", gap: 6, alignItems: "center" }}><Mail size={14} />{client.email}</span> : null}{client.phone ? <span className="row-subtitle" style={{ display: "flex", gap: 6, alignItems: "center" }}><Phone size={13} />{client.phone}</span> : null}{!client.email && !client.phone ? "—" : null}</td><td>{client.address ? <span style={{ display: "flex", gap: 6 }}><MapPin size={14} />{client.address}</span> : "—"}</td><td>{formatDate(client.updatedAt)}</td><td><RippleButton variant="ghost" size="icon" onClick={() => setEditing(client)} aria-label={`Editar ${client.name}`}><PencilLine /></RippleButton></td></tr>)}</tbody></table>}</div>
    <ClientDialog client={editing} open={Boolean(editing)} onOpenChange={(open) => { if (!open) setEditing(null); }} onSaved={async (message) => { push(message); setEditing(null); await load(); }} onConflict={() => setConflict(true)} />
    <RevisionConflictDialog open={conflict} onOpenChange={setConflict} onReload={() => { setConflict(false); setEditing(null); void load(); }} /><ToastViewport toasts={toasts} />
  </div>;
}

function ClientDialog({ client, open, onOpenChange, onSaved, onConflict }: { client: ClientRecord | "new" | null; open: boolean; onOpenChange: (open: boolean) => void; onSaved: (message: string) => void; onConflict: () => void }) {
  const existing = client && client !== "new" ? client : null; const [form, setForm] = useState({ name: "", taxId: "", email: "", phone: "", address: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { setForm({ name: existing?.name ?? "", taxId: existing?.taxId ?? "", email: existing?.email ?? "", phone: existing?.phone ?? "", address: existing?.address ?? "" }); setError(""); }, [existing, open]);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const payload = { name: form.name.trim(), ...(form.taxId ? { taxId: form.taxId } : {}), ...(form.email ? { email: form.email } : {}), ...(form.phone ? { phone: form.phone } : {}), ...(form.address ? { address: form.address } : {}) }; if (existing) await api.updateClient(existing.id, { ...payload, expectedRevision: existing.revision }); else await api.createClient(payload); onSaved(existing ? "Cliente actualizado" : "Cliente creado"); } catch (cause) { if (cause instanceof ApiError && cause.isRevisionConflict) onConflict(); else setError("Revisa los campos e inténtalo de nuevo."); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent title={existing ? "Editar cliente" : "Nuevo cliente"} description="Datos de contacto y facturación para el presupuesto." footer={<><DialogClose asChild><RippleButton variant="secondary">Cancelar</RippleButton></DialogClose><RippleButton type="submit" form="client-form" disabled={busy || !form.name.trim()}>{busy ? "Guardando…" : "Guardar cliente"}</RippleButton></>}><form id="client-form" onSubmit={submit} className="form-grid"><div className="field span-2"><label className="field-label" htmlFor="client-name">Nombre</label><input id="client-name" className="input" autoFocus value={form.name} onChange={(event) => update("name", event.target.value)} required /></div><div className="field"><label className="field-label" htmlFor="client-tax-id">NIF / CIF</label><input id="client-tax-id" className="input" value={form.taxId} onChange={(event) => update("taxId", event.target.value)} /></div><div className="field"><label className="field-label" htmlFor="client-phone">Teléfono</label><input id="client-phone" className="input" value={form.phone} onChange={(event) => update("phone", event.target.value)} /></div><div className="field span-2"><label className="field-label" htmlFor="client-email">Email</label><input id="client-email" className="input" type="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></div><div className="field span-2"><label className="field-label" htmlFor="client-address">Dirección</label><textarea id="client-address" className="textarea" value={form.address} onChange={(event) => update("address", event.target.value)} /></div>{error ? <p className="error-text span-2">{error}</p> : null}</form></DialogContent></Dialog>;
}
